express:
  port: 8080
  debug: 5858
  host: tsoa-sandbox

auth:
  jwt_secret: 'MySuperSecret'

mongo:
  mongo_uri: 'mongodb://tsoa-sandbox:password@ds245347.mlab.com:45347/tsoa-sandbox'

loglevel: info
